### PR TITLE
Qt header discovery & framework support; vendor simplecpp update

### LINKED ISSUE #276: Qt6 on macos: missing generated_cpp
Hi again,

I am trying to build pythonqt for Qt6 on linux and macos to [update the package on nixpkgs](https://github.com/NixOS/nixpkgs/pull/437521), but I am not able to generate the cpp on macos.

This issue can already be seen in the current CI: 
https://github.com/MeVisLab/pythonqt/actions/runs/16336586053/job/46149827921 :
```
Run cd generator
Please wait while source files are being generated...
Parsing typesystem file [:/trolltech/generator/build_all.txt]
"is not set. " Assuming standard binary install using frameworks.
WARNING(Generate) :: ShellImplGenerator: no java classes, skipping
WARNING(Generate) :: ShellHeaderGenerator: no java classes, skipping
PreProcessing - Generate [.preprocessed.tmp] using [:/trolltech/generator/qtscript_masterinclude.h] and include-paths [/Users/runner/work/pythonqt/Qt/5.9.9/clang_64/lib]
Building model using [.preprocessed.tmp]
Classes in typesystem: 0
Generated:
  - header....: 0 (0)
  - impl......: 0 (0)
  - modules...: 0 (0)
  - pri.......: 0 (0)

Done, 2 warnings (1851 known issues)
0s
Run actions/upload-artifact@v4
Warning: No files were found with the provided path: generated_cpp. No artifacts will be uploaded.
```

But this does not trigger any failure, so I guess this was not seen.

I tried to add a more explicit CI failure in #275 and #277, but that failed.

Anyways, could this be done ? In that case, I guess we should add macos to the "check generated_cpp" CI. Otherwise, we should probably add the generated_cpp for qt 6 to git.

### PR DESCRIPTION
**Pull request by jcfr**
This PR modernizes how the generator discovers Qt headers/frameworks and vendors a newer `simplecpp` with framework-aware search logic. Together these changes make builds robust on macOS (Qt frameworks) and cleaner across all platforms.

## Vendor `simplecpp` update

* Bumps `generator/simplecpp/{simplecpp.h, simplecpp.cpp}` to **patched-2025-08-30-37fa4f49b** (upstream: commontk/simplecpp@bfc53ad; previously danmar/simplecpp@37fa4f4).
* Re-applies local patch: `generator/simplecpp/do_not_stop_on_error.patch`.
* Introduces a typed, ordered search path API:

  * `DUI::PathKind { Include, SystemInclude, Framework, SystemFramework }`
  * `DUI::searchPaths` plus helpers `addIncludePath`, `addSystemIncludePath`, `addFrameworkPath`, `addSystemFrameworkPath`
  * Back-compat: if `searchPaths` is empty, legacy `includePaths` is mirrored as `Include`.
* Adds Apple framework resolution for `#include <Pkg/Hdr.h>` → `<Pkg.framework/Headers/Hdr.h>` (and `PrivateHeaders` fallback).
* Interleaves `-I` and `-F` in the original CLI order; handles `-isystem` and `-iframework`.

**Upstream compare:** [https://github.com/commontk/simplecpp/compare/37fa4f4...bfc53ad](https://github.com/commontk/simplecpp/compare/37fa4f4...bfc53ad)

> [!NOTE]
> This changes are vendored from the `commontk/simplecpp` fork including commit backported from:
> * https://github.com/danmar/simplecpp/pull/511

## Generator: discover Qt headers via `QLibraryInfo`

* Prefers `QLibraryInfo::HeadersPath`; falls back to `$QTDIR/include` if needed.
* Accepts include roots from:

  * `PYTHONQT_INCLUDE` (path list; validated)
  * `--include-paths` (validated)
* Probes and appends existing module subdirs under the Qt include root: `QtCore`, `QtGui`, `QtNetwork`, `QtOpenGL`, `QtXml`.
* Starts using `DUI::addIncludePath(...)` instead of pushing to the legacy `includePaths`.
* Removes hardcoded macOS `/Library/Frameworks/.../Headers` assumptions (to defer to new framework discovery).

## Generator: discover Qt framework paths dynamically (macOS)

* New `getFrameworkDirectories(...)` collects framework/library search roots from:

  * `.` (cwd)
  * `PYTHONQT_FRAMEWORK` (validated)
  * `--framework-paths` (validated)
  * `${QTDIR}/lib/<Module>.framework` when present, plus `${QTDIR}/lib`
  * `QLibraryInfo::LibrariesPath` when available
* Passes these paths to the preprocessor using `DUI::addFrameworkPath(...)`.

## Generator: detect Qt version from frameworks on macOS

* `getQtVersion(...)` now accepts either header include directories or framework roots.
* On macOS, probes `Versions/A/Headers/qtcoreversion.h` when given a framework root (e.g., `.../QtCore.framework`).
* Tries include paths first, then framework paths; aborts early with a clear error message if neither yields a version.

---

This pull request supersedes the following ones:
* #271 
* #299

---

This pull request fixes the following issues:

* Fixes #276

### CODE REVIEW

**Comment by jcfr** [comment]
@jamesobutler Now this has been proposed upstream, we will be able to contribute `CMakeLists.txt` changes including Qt6 support, along with finalizing CTK & Slicer Qt updates :rocket:

File: generator/simplecpp/simplecpp.h [hunk 1]
```diff
@@ -395,13 +395,70 @@ namespace simplecpp {
...
+
+        // Back-compat: legacy -I list. If searchPaths is empty at use time,
+        // consumers should mirror includePaths -> searchPaths as Include.
         std::list<std::string> includePaths;
+        // New: ordered, interleaved search paths with kind.
+        std::vector<SearchPath> searchPaths;
+
         std::list<std::string> includes;
         std::string std;
         bool clearIncludeCache;
```
Comment (mrbean-bremen) [inline generator/simplecpp/simplecpp.h:464]: As these are upstream changes, `README.txt` should also be adapted.

File: generator/main.cpp [hunk 2]
```diff
@@ -67,77 +68,157 @@ void displayHelp(GeneratorSet *generatorSet);
...
-      if (!commandLineIncludes.isEmpty())
-        includes += commandLineIncludes.split(pathSplitter, Qt::SkipEmptyParts);
-      for (auto it = includes.begin(); it != includes.end();)
-      {
-        if (!QDir(*it).exists())
-        {
-          qWarning() << "Include path " << it->toUtf8() << " does not exist, ignoring it.";
-          it = includes.erase(it);
+      // From env var PYTHONQT_INCLUDE
+      const QString envInclude = qEnvironmentVariable("PYTHONQT_INCLUDE");
```
Comment (mrbean-bremen) [inline generator/main.cpp:92]: `qEnvironmentVariable` has been introduced in Qt 5.10, so the tests using 5.9 now fail.

File: generator/main.cpp [hunk 3]
```diff
@@ -67,77 +68,157 @@ void displayHelp(GeneratorSet *generatorSet);
...
-            includes << (frameworkDir + "/QtOpenGL.framework/Headers");
-            includes << frameworkDir;
-#else
-        qWarning() << reason << "This may cause problems with finding the necessary include files.";
-#endif
+      // Prefer QLibraryInfo (works without QTDIR)
+      QString qtInclude = QLibraryInfo::location(QLibraryInfo::HeadersPath);
+      if (!isDir(qtInclude)) {
+        // Fallback to QTDIR/include
+        const QString qtDir = qEnvironmentVariable("QTDIR");
```
Comment (mrbean-bremen) [inline generator/main.cpp:122]: same here and below

**Comment by jcfr** [comment]
@mrbean-bremen  Thanks for the review :pray: I will revisit and update shortly :rocket:

File: generator/main.cpp [hunk 4]
```diff
@@ -67,77 +68,162 @@ void displayHelp(GeneratorSet *generatorSet);
...
```
Comment (usiems) [inline generator/main.cpp:127]: I dislike a little bit the fact that now we can't generate the bindings for a different Qt version than the version with which the generator was built. Sure, this is a little bit of a corner case, but I know that I have used this at some time during development.

Could we get another override mechanism for the Qt include directory?

Comment (jcfr) [reply generator/main.cpp:127]: > I dislike a little bit the fact that now we can't generate the bindings for a different Qt version than the version with which the generator was built. Sure, this is a little bit of a corner case, but I know that I have used this at some time during development.

For future reference, this has been addressed in https://github.com/MeVisLab/pythonqt/pull/313
